# Optional configs used by Nextstrain team
# Params for uploads
# AWS S3 Bucket with prefix
s3_dst: 's3://nextstrain-data/files/workflows/rsv'
upload:
  # Upload params for AWS S3
  s3:
    # Files to upload to S3 that are in the `data` directory
    files_to_upload: [
      'genbank.ndjson',
      'sequences.ndjson',
      'a/metadata.tsv',
      'a/sequences.fasta',
      'b/metadata.tsv',
      'b/sequences.fasta'
    ]
    # Remote file names for the files to upload, must be in the same order as local files above
    remote_file_names: [
      'genbank.ndjson.xz',
      'sequences.ndjson.xz',
      'a/metadata.tsv.gz',
      'a/sequences.fasta.xz',
      'b/metadata.tsv.gz',
      'b/sequences.fasta.xz'
    ]
    cloudfront_domain: 'data.nextstrain.org'
